title: Place
description: A place for everything
owner_name: coolCodingPeople
github_username: CoolCodingPeople
baseurl: "/place"
repository: coolcodingpeople/place2
#remote_theme: jekyll/minima
remote_theme: pages-themes/dinky@0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
